

MAX_DIGITS = 10
PRODUCT_PRICE_DECIMAL_PLACES = 2
PRODUCT_PRICE_MAX_DIGITS = 10
REDIRECT_URL_LENGTH = 300
CHARFIELD_MIN_LENGTH = 300
PAYPAL_API_URL_LENGTH = 512
PAYPAL_AUTH_GRANT_TYPE_HEADER = "client_credentials"
PAYPAL_AUTH_HEADER_CONTENT_TYPE = "application/x-www-form-urlencoded"
PAYPAL_AUTH_CLIENT_ID_KEY = "CLIENT_ID"
PAYPAL_AUTH_HEADER_PREFIX = "Basic "
FAILED_REASON_CUSTOMER_DECLINED = 0
FAILED_REASON_UNSUFFICIENT_FUND = 1
FAILED_REASON_UNKNOWN_SENDER = 2
FAILED_REASON_BAD_REQUEST = 3
FAILED_REASON_TIMEOUT = 4
FAILED_REASON_ORDER_CANCELLED = 5
FAILED_REASON_LIST = [FAILED_REASON_CUSTOMER_DECLINED, FAILED_REASON_UNSUFFICIENT_FUND, FAILED_REASON_UNKNOWN_SENDER, FAILED_REASON_BAD_REQUEST,FAILED_REASON_TIMEOUT, FAILED_REASON_ORDER_CANCELLED]

FAILED_REASONS = (
    (FAILED_REASON_CUSTOMER_DECLINED, _('CUSTOMER DECLINED')),
    (FAILED_REASON_UNSUFFICIENT_FUND, _('UNSUFFICIENT FUND')),
    (FAILED_REASON_UNKNOWN_SENDER, _('UNKNOWN SENDER')),
    (FAILED_REASON_BAD_REQUEST, _('BAD REQUEST')),
    (FAILED_REASON_TIMEOUT, _('TIMEOUT')),
    (FAILED_REASON_ORDER_CANCELLED, _('ORDER CANCELLED')),
)